config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :projects do
  resources :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include Redmine::SafeAttributes

  validates :name, presence: true

  safe_attributes "name", "project_id", "custom_fields", "custom_field_values"
  acts_as_customizable
  acts_as_attachable delete_permission: :delete_contacts, view_permission: :view_contacts
  belongs_to :project

  acts_as_event datetime: :updated_at,
                description: nil,
                title: proc { |o| "#{l(:label_contact_name)} #{o.name}" },
                url: proc { |o| { controller: "contacts", action: "show", id: o, project_id: o.project_id } },
                author: nil

  acts_as_activity_provider type: "contacts",
                            permission: nil,
                            timestamp: :updated_at,
                            author_key: nil,
                            scope: joins(:project)

  acts_as_searchable columns: "#{table_name}.name", date_column: "created_at"

  scope :visible, lambda { |*args|
                    joins(:project)
                      .where(Project.allowed_to_condition(args.shift || User.current, :view_contacts, *args))
                  }
end

app/models/contact_custom_field.rb
class ContactCustomField < CustomField
  def type_name
    :label_contact_plural
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  helper :custom_fields
  helper :attachments
  include AttachmentsHelper

  before_action :find_contact, only: %i[edit update destroy show]
  before_action :find_optional_project

  def index
    @contacts = Contact.all.where(project_id: @project.id)
  end

  def new
    @contact = Contact.new
    @contact.safe_attributes = params[:contact]
  end

  def create
    @contact = Contact.new
    @contact.safe_attributes = params[:contact]
    @contact.save_attachments(params[:attachments])
    if @contact.save
      render_attachment_warning_if_needed(@contact)
      flash[:notice] = l(:notice_successful_create)
      redirect_to project_contacts_path(@project)
    else
      render action: "new"
    end
  end

  def show; end

  def edit; end

  def update
    @contact.safe_attributes = params[:contact]
    @contact.save_attachments(params[:attachments])
    if @contact.update_attributes(params[:contact])
      render_attachment_warning_if_needed(@contact)
      flash[:notice] = l(:notice_successful_update)
      redirect_to project_contacts_path(@project)
    else
      render action: "edit", project_id: @contact.project_id
    end
  end

  def destroy
    if @contact.destroy
      flash[:notice] = l(:notice_successful_delete)
      redirect_to project_contacts_path(@project)
    else
      flash[:error] = l(:notice_unsuccessful_save)
    end
  end

  private

  def find_contact
    @contact = Contact.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def contact_url(contact)
    project_id = @project.blank? ? contact.project : @project
    { controller: "contacts", action: "show", project_id: project_id, id: contact.id }
  end
end

app/views/contacts/_form.erb
<%= error_messages_for 'contact' %>

<%= form_for ([@project, @contact]) do |f| %>
    <%= f.label :name %>*<br>
    <%= f.text_field :name %><br>
    <%= f.hidden_field :project_id, value: @project.id %><br>
    <% @contact.custom_field_values.each do |value| %>
        <p><%= custom_field_tag_with_label :contact, value %></p>
    <% end %>
    <div class="box">
      <p>
        <label><%= l(:label_attachment_plural) %></label>
        <%= render partial: 'attachments/form' %>
      </p>
    </div>
    <%= f.submit %>
<% end %>

app/views/contacts/edit.html.erb
<%= render 'form' %>

app/views/contacts/index.html.erb
<h2><%= l(:label_contact_plural) %></h2>

<% unless @contacts.empty? %>
  <table class="list">
    <% @contacts.each do |contact| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= link_to contact.name, contact_url(contact) %></td>
        <td align="right">
          <small>
            <% if User.current.allowed_to?(:edit_contact,@project) %>
            <%= link_to l(:button_edit), edit_project_contact_path(@project, contact),
                                 title: l(:button_edit),
                                 class: 'icon-only icon-edit' %>
            <%end%>
            <% if User.current.allowed_to?(:delete_contacts, @project) %>
            <%= link_to l(:button_delete), project_contact_path(@project, contact),
                                    data: {confirm: l(:text_are_you_sure)},
                                    method: :delete,
                                    title: l(:button_delete),
                                    class: 'icon-only icon-del' %>
            <% end %>
          </small>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p class="nodata"><%=l(:label_no_data)%></p>
<% end %>

<% if User.current.allowed_to?(:create_contact,@project) %>
  <%= link_to 'New contact', new_project_contact_path(@project) %><br>
<%end%>

app/views/contacts/new.html.erb
<%= render 'form' %> 

app/views/contacts/show.html.erb
<%= link_to_attachments @contact, thumbnails: false, author: true %>

<%= link_to 'back', project_contacts_path %>